// assets/images/cardImages.ts

const cardImages: Record<string, any> = {
    // Major Arcana
    'the-fool': require('./cards/the-fool.png'),
    'the-magician': require('./cards/the-magician.png'),
    'the-high-priestess': require('./cards/the-high-priestess.png'),
    'the-empress': require('./cards/the-empress.png'),
    'the-emperor': require('./cards/the-emperor.png'),
    'the-hierophant': require('./cards/the-hierophant.png'),
    'the-lovers': require('./cards/the-lovers.png'),
    'the-chariot': require('./cards/the-chariot.png'),
    'strength': require('./cards/strength.png'),
    'the-hermit': require('./cards/the-hermit.png'),
    'wheel-of-fortune': require('./cards/wheel-of-fortune.png'),
    'justice': require('./cards/justice.png'),
    'the-hanged-man': require('./cards/the-hanged-man.png'),
    'death': require('./cards/death.png'),
    'temperance': require('./cards/temperance.png'),
    'the-devil': require('./cards/the-devil.png'),
    'the-tower': require('./cards/the-tower.png'),
    'the-star': require('./cards/the-star.png'),
    'the-moon': require('./cards/the-moon.png'),
    'the-sun': require('./cards/the-sun.png'),
    'judgement': require('./cards/judgement.png'),
    'the-world': require('./cards/the-world.png'),
  
    // Cups
    'ace-of-cups': require('./cards/ace-of-cups.png'),
    'two-of-cups': require('./cards/two-of-cups.png'),
    'three-of-cups': require('./cards/three-of-cups.png'),
    'four-of-cups': require('./cards/four-of-cups.png'),
    'five-of-cups': require('./cards/five-of-cups.png'),
    'six-of-cups': require('./cards/six-of-cups.png'),
    'seven-of-cups': require('./cards/seven-of-cups.png'),
    'eight-of-cups': require('./cards/eight-of-cups.png'),
    'nine-of-cups': require('./cards/nine-of-cups.png'),
    'ten-of-cups': require('./cards/ten-of-cups.png'),
    'page-of-cups': require('./cards/page-of-cups.png'),
    'knight-of-cups': require('./cards/knight-of-cups.png'),
    'queen-of-cups': require('./cards/queen-of-cups.png'),
    'king-of-cups': require('./cards/king-of-cups.png'),
  
    // Pentacles
    'ace-of-pentacles': require('./cards/ace-of-pentacles.png'),
    'two-of-pentacles': require('./cards/two-of-pentacles.png'),
    'three-of-pentacles': require('./cards/three-of-pentacles.png'),
    'four-of-pentacles': require('./cards/four-of-pentacles.png'),
    'five-of-pentacles': require('./cards/five-of-pentacles.png'),
    'six-of-pentacles': require('./cards/six-of-pentacles.png'),
    'seven-of-pentacles': require('./cards/seven-of-pentacles.png'),
    'eight-of-pentacles': require('./cards/eight-of-pentacles.png'),
    'nine-of-pentacles': require('./cards/nine-of-pentacles.png'),
    'ten-of-pentacles': require('./cards/ten-of-pentacles.png'),
    'page-of-pentacles': require('./cards/page-of-pentacles.png'),
    'knight-of-pentacles': require('./cards/knight-of-pentacles.png'),
    'queen-of-pentacles': require('./cards/queen-of-pentacles.png'),
    'king-of-pentacles': require('./cards/king-of-pentacles.png'),
  
    // Swords
    'ace-of-swords': require('./cards/ace-of-swords.png'),
    'two-of-swords': require('./cards/two-of-swords.png'),
    'three-of-swords': require('./cards/three-of-swords.png'),
    'four-of-swords': require('./cards/four-of-swords.png'),
    'five-of-swords': require('./cards/five-of-swords.png'),
    'six-of-swords': require('./cards/six-of-swords.png'),
    'seven-of-swords': require('./cards/seven-of-swords.png'),
    'eight-of-swords': require('./cards/eight-of-swords.png'),
    'nine-of-swords': require('./cards/nine-of-swords.png'),
    'ten-of-swords': require('./cards/ten-of-swords.png'),
    'page-of-swords': require('./cards/page-of-swords.png'),
    'knight-of-swords': require('./cards/knight-of-swords.png'),
    'queen-of-swords': require('./cards/queen-of-swords.png'),
    'king-of-swords': require('./cards/king-of-swords.png'),
  
    // Wands
    'ace-of-wands': require('./cards/ace-of-wands.png'),
    'two-of-wands': require('./cards/two-of-wands.png'),
    'three-of-wands': require('./cards/three-of-wands.png'),
    'four-of-wands': require('./cards/four-of-wands.png'),
    'five-of-wands': require('./cards/five-of-wands.png'),
    'six-of-wands': require('./cards/six-of-wands.png'),
    'seven-of-wands': require('./cards/seven-of-wands.png'),
    'eight-of-wands': require('./cards/eight-of-wands.png'),
    'nine-of-wands': require('./cards/nine-of-wands.png'),
    'ten-of-wands': require('./cards/ten-of-wands.png'),
    'page-of-wands': require('./cards/page-of-wands.png'),
    'knight-of-wands': require('./cards/knight-of-wands.png'),
    'queen-of-wands': require('./cards/queen-of-wands.png'),
    'king-of-wands': require('./cards/king-of-wands.png'),
  };
  
  export default cardImages;
  